### PR TITLE
This fixes the bean not being created, missing scope.

### LINKED ISSUE #50: TCK fails 'Unsatisfied dependencies'
```
arquillianBeforeClass(org.eclipse.microprofile.fault.tolerance.tck.FallbackTest)  Time elapsed: 0.032 sec  <<< FAILURE!
org.jboss.weld.exceptions.DeploymentException: 
WELD-001408: Unsatisfied dependencies for type MyBean with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.eclipse.microprofile.fault.tolerance.tck.retry.clientserver.FallbackA.myBean
  at org.eclipse.microprofile.fault.tolerance.tck.retry.clientserver.FallbackA.myBean(FallbackA.java:0)
```

Looking at the JAR, it's not a valid bean archive (based on the SE spec portions at least).  It has no `beans.xml`.

### PR DESCRIPTION
**Pull request by johnament**
Fixed a test issue where the test order was throwing off results.

This closes #50

Signed-off-by: John D. Ament <john.d.ament@gmail.com>

### CODE REVIEW

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java [hunk 1]
```diff
@@ -54,49 +55,48 @@ public static WebArchive deploy() {
...
-       
+
     }
-    
+
     /**
      * The fallbakHandler is the wrong type. This should failed the validation check.
      */
-    @Test
+    @Test(priority = 2)
```
Comment (johnament) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java]: Note that without this change, I was seeing cases where this test ran first, throwing off the counts for `testFallbackSuccess`.
