### PR TITLE
specify the meaning of overlapping retryOn and abortOn

### LINKED ISSUE #442: clarify retryOn/abortOn behavior of @Retry
As we discovered, both SmallRye and OpenLiberty behave the same when it comes to overlapping set of throwables in `retryOn` and `abortOn`: blacklist wins over whitelist. We agreed to codify this behavior.

(Where `retryOn` is the "whitelist" and `abortOn` is the "blacklist". The guiding principle here seems to be: the normal [= white] thing to do for `@Retry` in case of an exception is to retry. You can configure an exception [= black] to that behavior.)

### LINKED ISSUE #449: Revisit behaviour when a custom throwable is specified for retryOn or abortOn
In #441, we also said that a method throwing a custom `Throwable` results in non-portable behaviour, and in reviewing that, I found some issues with what happens when the user _specifies_ a custom Throwable in an annotation.

The Javadoc for the `retryOn` and `abortOn` parameters for `@Retry` says

> Only a type assignable from {@link java.lang.Error} or {@link java.lang.Exception} can be specified.
> Specifying a custom java.lang.Throwable will be ignored.

This has some interesting consequences:
1. If the user does `@Retry(retryOn=MyCustomThrowable.class)`, it gets ignored and no Retries occur. Implementations could emit a warning here, but there's no deployment time exception.
1. If the user does `@Retry(retryOn=Throwable.class)`, it also gets ignored (as `Throwable` is not a subclass of `Error` or `Exception`). Again, no deployment error.
   * It's worth noting that doing this is a bad idea. An `Error` is often something fairly fatal (like OOM) so retrying is not likely to be helpful.
1. If we want to be consistent, then we should define the `@CircuitBreaker` `failOn` and `skipOn` parameters in the same way. However, this would mean that the _default_ configuration of `@CircuitBreaker(failOn=Throwable.class)` would be ignored, obviously not the desired behaviour.

### PR DESCRIPTION
**Pull request by Ladicek**
Signed-off-by: Ladislav Thon <lthon@redhat.com>

Resolves #442.
Resolves #449.

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java [hunk 1]
```diff
@@ -104,14 +104,24 @@
...
     @Nonbinding
     Class<? extends Throwable>[] retryOn() default { Exception.class };
 
     /**
-     * 
+     *
      * @return Specify the failure to abort on. Only a type assignable from {@link java.lang.Error} or {@link java.lang.Exception} can be specified.
      * Specifying a custom java.lang.Throwable will be ignored.
+     * <p>
+     * Whenever the set of retry-on exceptions overlaps with the set of abort-on exceptions, {@code abortOn} takes precedence.
```
Comment (Emily-Jiang) [inline api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: retry-on -> `retryOn`, abort-on -> `abortOn`

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java [hunk 2]
```diff
@@ -104,14 +104,24 @@
...
+     * Overlapping means not only that the same type is present in both sets, but also that one set contains a type which
```
Comment (Emily-Jiang) [inline api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: I will rephrase to be:
If an exception is thrown, it first matches `{code abortOn}`. If the exception is listed in the `{code abortOn}` or can be assigned to one exception in the list, the exception will be aborted from the retry operation. 
If not, the exception will be matched against `{code retryOn}. If the exception is listed in the `{code retryOn}`  or can be assigned to one exception in the list, the exception will trigger the retry operation.

Comment (Ladicek) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: I did a more significant rewording. Please take another look.

**Comment by Azquelt** [comment]
@genie-microprofile test this please

**Comment by Azquelt** [comment]
Would it make more sense to put this information at the class level rather than on both of the parameters?

**Comment by Ladicek** [comment]
I thought about that and I think that users are more likely to search for details of `retryOn` / `abortOn` in their respective documentation, rather then the general `@Retry` documentation. But we can add `@see #retryOn` or something like that.

**Comment by Azquelt** [comment]
@genie-microprofile test this please

**Comment by Ladicek** [comment]
Updated. This is now similar to #448: the behavior is described as a set of rules in the main annotation class javadoc, not in the `retryOn` and `abortOn` attributes javadoc. As opposed to #448, I left out the constant mentions of "custom throwables result in non-portable behavior", as that's already explained in the specification and doesn't add value here.

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java [hunk 3]
```diff
@@ -30,9 +30,18 @@
...
- * retry counts. Any invalid config value causes 
+ * The Retry annotation to define the number of the retries. Any invalid config value causes
  * {@link org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException}.
+ * <p>
+ * When a method returns and the retry policy is present, the following rules are applied:
+ * <ol>
+ * <li>If the method returns normally (doesn't throw), the result is simply returned.
+ * <li>Otherwise, if the thrown object is assignable to any value in the {@link #abortOn()} parameter, the thrown object is rethrown.
+ * <li>Otherwise, if the thrown object is assignable to any value in the {@link #retryOn()} parameter, the method call is retried
+ *     (up to configured {@link #maxRetries() number of times}).
```
Comment (Emily-Jiang) [inline api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: I suggest to delete the above line as it does not add much info. It could be up to configured maxRetries or maxDuration.

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java [hunk 4]
```diff
@@ -101,17 +110,19 @@
 
 
     /**
+     * The list of exception types which should trigger a retry.
      *
-     * @return Specify the failure to retry on. Only a type assignable from {@link java.lang.Error} or {@link java.lang.Exception} can be specified.
-     * Specifying a custom java.lang.Throwable will be ignored.
```
Comment (Emily-Jiang) [inline api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: Why did you delete this sentence?

Comment (Emily-Jiang) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: I sensed the reason when I saw your comments on the PR from @Azquelt. I advise to put the info back on as many people told me that they don't read spec and rely on JavaDoc. For some important info, we need to put on JavaDoc, which is why JDK classes have long javadocs. In Config, I have PR to add some important info from spec to JavaDoc.

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java (hunk 3 above)
Comment (Ladicek) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: Good point.

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java (hunk 4 above)
Comment (Ladicek) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: I propose to _allow_ specifying `Throwable`.

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java (hunk 3 above)
Comment (Ladicek) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: Done.

Comment (Azquelt) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: Should we extend this list to also cover `maxRetries` and `maxDuration`? Possibly in another PR.

File: api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java (hunk 4 above)
Comment (Emily-Jiang) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: What do you mean @Ladicek ! I prefer the sentences are not deleted.

Comment (Ladicek) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: What I mean is that it doesn't make any sense to ignore `@Retry(retryOn = Throwable.class)`.

Comment (Azquelt) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: I agree with @Ladicek, the current doc specifies that `@Retry(retryOn = Throwable.class)` will be ignored, which is very unintuitive.

We already specify that if a method throws an object which isn't a subclass of `Error` or `Exception` then the behaviour is undefined, we don't also need to have a restriction here that states it must be _ignored_.

I think that `@Retry(retryOn = Throwable.class` should retry on `Exception`, `Error` and all their subclasses. If a throwable that doesn't extend `Exception` or `Error` is thrown, then non-portable behaviour results (as specified elsewhere).

Comment (Emily-Jiang) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: @Ladicek I talked with @Azquelt . The bit mentioned in his last paragraph needs to be in the JavaDoc. The current Javadoc does not convene that info, as I think this info is very important.

Comment (Ladicek) [reply api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java]: Updated.

I actually consider this a very rare corner case that _doesn't_ warrant 3 mentions in a javadoc of this annotation, but so be it.
