### PR TITLE
This PR replaces all expected RuntimeExceptions with TestException. T…

### LINKED ISSUE #620: The use of expected RuntimeExceptions in the TCK can cause false positives
In our build system I noticed some tests failing with a RuntimeException. This is concerning because if our build system creates unwanted runtime exceptions it might create them inside the try blocks where a RuntimeException is expected.

To fix this all expected RuntimeExceptions should be replaced with TestException.

### PR DESCRIPTION
**Pull request by benjamin-confino**
…his is because I saw some genuine RuntimeExceptions causing failures in our build system and if runtime exceptions can appear where they are not expected the wrong runtime exception may appear where a runtime exception is expected

Where a runtime exception is not expected it also updates the error message to include the details of that exception

fixes #620

### CODE REVIEW

**Comment by Azquelt** [comment]
I think instances like this should also be updated: https://github.com/eclipse/microprofile-fault-tolerance/pull/619/files#diff-75e65464c0fe1fb4456a2b1d045d03b43dbc7ed637603883d5f8292dccdd5b07L102

This test should expect a TestException on iteration 1,2,3,7,8 and 9. It should fail with a different error (in the surrounding catch block) if another exception is thrown.

**Review by Emily-Jiang — APPROVED** [review]
LGTM

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncTimeoutTest.java [hunk 1]
```diff
@@ -78,7 +79,8 @@ public static WebArchive deploy() {
 
         JavaArchive testJar = ShrinkWrap
                 .create(JavaArchive.class, "ftAsyncTimeout.jar")
-                .addClasses(AsyncTimeoutClient.class, AsyncClassLevelTimeoutClient.class, Connection.class)
+                .addClasses(AsyncTimeoutClient.class, AsyncClassLevelTimeoutClient.class, Connection.class,
+                        TestException.class)
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncTimeoutTest.java:83]: Unsure why `TestException` is needed in this app, none of the other classes in the app appear to reference it.

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java [hunk 2]
```diff
@@ -81,17 +82,17 @@ public void testFallbackSuccess() {
             String result = fallbackClient.serviceA();
             Assert.assertTrue(result.contains("serviceA"),
                     "The message should be \"fallback for serviceA\"");
-        } catch (RuntimeException ex) {
-            Assert.fail("serviceA should not throw a RuntimeException in testFallbackSuccess");
+        } catch (TestException ex) {
+            Assert.fail("serviceA should not throw a RuntimeException in testFallbackSuccess", ex);
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java:86]:
```suggestion
        } catch (TestException ex) {
            Assert.fail("serviceA should not throw a TestException in testFallbackSuccess", ex);
```

Comment (Azquelt) [reply tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java:86]: Similar messages throughout this class should also change.

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java [hunk 3]
```diff
@@ -81,17 +82,17 @@ public void testFallbackSuccess() {
...
         Assert.assertEquals(fallbackClient.getCounterForInvokingServiceA(), 2,
                 "The execution count should be 2 (1 retry + 1)");
         try {
             String result = fallbackClient.serviceB();
             Assert.assertTrue(result.contains("serviceB"),
                     "The message should be \"fallback for serviceB\"");
-        } catch (RuntimeException ex) {
-            Assert.fail("serviceB should not throw a RuntimeException in testFallbackSuccess");
+        } catch (TestException ex) {
+            Assert.fail("serviceB should not throw a RuntimeException in testFallbackSuccess", ex);
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java:95]: The changes to the `catch` blocks in this test are good, but the following methods in other classes should be updated to match:

- `FallbackClient.nameService()`
- `FallbackOnlyClient.nameService()`
- `FallbackWithBeanClient.nameService()`

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClassLevelClientAbortOn.java [hunk 4]
```diff
@@ -63,7 +64,7 @@ private void writingService() {
         counterForInvokingWritingService++;
         try {
             Thread.sleep(100);
-            throw new RuntimeException("WritingService failed");
+            throw new TestException("WritingService failed");
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClassLevelClientAbortOn.java:67]: `serviceB` (just above this change in the file), should be updated to abortOn a `TestException` rather than a `RuntimeException`.

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java [hunk 5]
```diff
@@ -62,6 +63,9 @@
  */
 public class RetryConditionTest extends Arquillian {
 
+    private final static String SIMULATED_EXCEPTION_MESSAGE = "Simulated error";
+    private final static String SIMULATED_RUNTIME_EXCEPTION_MESSAGE = "Test Exception - Simulated error";
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java:67]: Changing these strings to constants is fine, but these strings are also used in `AsyncRetryClient`.

Please either leave the strings in the tests, or update `AsyncRetryClient` to use the same constants. Using the constants in one place but not the other gives you none of the benefits of using a constant and makes it harder to see that both parts of the test are using the same string.

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java [hunk 6]
```diff
@@ -272,11 +273,11 @@ private void checkServiceCall(int nbExpectedRetries, RetryService service, Strin
                             RetryVisibilityTest.class.getSimpleName(),
                             testName,
                             expectedNbCalls));
-        } catch (RuntimeException ex) {
+        } catch (TestException ex) {
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java:276]: Most changes in this class should be undone.

This class is using `IOException` as its expected exception - similar to the way we're using `TestException` in other classes.

If anything, this catch block could change from `RuntimeException` to just `Exception` - it's just adding more information about unexpected thrown exceptions.

You _could_ change `IOException` to `TestException` in this class and in `BaseRetryOnClassService`.

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java [hunk 7]
```diff
@@ -272,11 +273,11 @@ private void checkServiceCall(int nbExpectedRetries, RetryService service, Strin
...
             Assert.fail(String.format("no %s exception should have been thrown in %s#%s",
                     ex.getClass().getName(),
                     RetryVisibilityTest.class.getSimpleName(),
-                    testName));
+                    testName), ex);
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java:280]: This change can stay.

**Review by Azquelt — CHANGES_REQUESTED** [review]
See comments above.

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java [hunk 8]
```diff
@@ -264,19 +263,19 @@ private void checkServiceCall(int nbExpectedRetries, RetryService service, Strin
...
+        } catch (TestException re) {
             Assert.assertEquals(
                     service.getNumberOfServiceCalls(),
                     expectedNbCalls,
                     String.format("in %s#%s service() should have been called exactly %d times",
                             RetryVisibilityTest.class.getSimpleName(),
                             testName,
                             expectedNbCalls));
-        } catch (RuntimeException ex) {
+        } catch (TestException ex) {
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java:274]: You've changed this test to use `TestException` rather than `IOException` which is fine, but this second catch block still needs to change to catch either `Exception` or `RuntimeException`, since this catch block is dealing with _unexpected_ exceptions.

Comment (Azquelt) [reply tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java:274]: I'm actually surprised that having two catch blocks for the same exception type isn't a compile error.

**Comment by Azquelt** [comment]
@eclipse-microprofile-bot test this please

**Comment by Azquelt** [comment]
@eclipse-microprofile-bot test this please

**Comment by Azquelt** [comment]
@eclipse-microprofile-bot test this please
