### PR TITLE
Fix tests where ms had been changed to ns inconsistently

### LINKED ISSUE #373: TCK uses currentTimeMillis
A couple of TCK tests still use `System.currentTimeMillis()` for measuring the time a thread takes. It is recommended that `nanoTime()` is used instead as nanoTime is independent of the system clock and, for example, switching to daylight savings time will not affect the tests.

### PR DESCRIPTION
**Pull request by Azquelt**
I've used Duration where possible to avoid having the same mistake
happen again.

Also fix RetryClientWithDelay so that it records the delay between
subsequent executions correctly.

Fixes #373

I also came across an issue where we were measuring times incorrectly in `testAsyncClassLevelTimeout` so I've fixed that too.

Signed-off-by: Andrew Rouse <anrouse@uk.ibm.com>

### CODE REVIEW

File: tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java [hunk 1]
```diff
@@ -35,30 +36,35 @@
...
     //there should be at least 4 retries
     @Retry(delay = 400, maxDuration= 3200, jitter= 400, maxRetries = 10)
     public Connection serviceA() {
         return connectionService();
     }
+    
     //simulate a backend service
     private Connection connectionService() {
-       // the time delay between each invocation should be 0-800ms
-       if (timestampForConnectionService != 0) {
```
Comment (Azquelt) [inline tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java]: Note that in the old revision, this condition would never be met because `timestampForConnectionService` would only be set to a non-zero value within this if-block.
